#ifndef TIME_TEST_H
#define TIME_TEST_H
#include "SharedPtr.hpp"
#include "UniquePtr.hpp"
#include "profiler.hpp"
#include <memory>
void makePlentyOfSharedPtr();
void makePlentyOfStdShared();
void makePlentyOfUniquePtr();
void makePlentyOfStdUnique();
void makeTimeTest();
std::vector<double> generateArrayUniqPtr();
std::vector<double> generateArrayStdUnique_ptr();
std::vector<double> generateArraySharedPtr();
std::vector<double> generateArrayStdSharedPtr();
#endif /*TIME_TEST_H*/